export type PeriodData = {
  ID: string;
  RESULTID: string;
  BATTERYLOW: string;
  DURATIONSEC: string;
  ENDDATETIME: string | Date;
  NOTES: string;
  OVERLOAD: string;
  PAUSEDURATIONSEC: string;
  RESPONSE: string;
  RUNNO: string;
  STARTDATETIME: string;
  OCTAVECOUNT: string;
  LAFMAX: number;
  LAFMAXTIME: Date | string;
  LAFMIN: number;
  LAFMINTIME: string;
  LAIMAX: string;
  LAIMAXTIME: string;
  LAIMIN: string;
  LAIMINTIME: string;
  LASMAX: string;
  LASMAXTIME: string;
  LASMIN: string;
  LASMINTIME: string;
  LCFMAX: string;
  LCFMAXTIME: string;
  LCFMIN: string;
  LCFMINTIME: string;
  LCIMAX: string;
  LCIMAXTIME: string;
  LCIMIN: string;
  LCIMINTIME: string;
  LCSMAX: string;
  LCSMAXTIME: string;
  LCSMIN: string;
  LCSMINTIME: string;
  LZFMAX: string;
  LZFMAXTIME: string;
  LZFMIN: string;
  LZFMINTIME: string;
  LZIMAX: string;
  LZIMAXTIME: string;
  LZIMIN: string;
  LZIMINTIME: string;
  LZSMAX: string;
  LZSMAXTIME: string;
  LZSMIN: string;
  LZSMINTIME: string;
  LAPK: string;
  LAPKTIME: string;
  LCPK: string;
  LCPKTIME: string;
  LZPK: string;
  LZPKTIME: string;
  LAE: string;
  LAEQ: string;
  LAEQT80: string;
  LAFTM3: string;
  LAFTM5: string;
  LAIEQ: string;
  LAITM3: string;
  LAITM5: string;
  LCEQ: string;
  LCEQSUBLAEQ: string;
  LEPD: string;
  LEX8H: string;
  LZEQ: string;
  LAVGQ4: string;
  LAVGTHRESHOLD: string;
  TWAQ4: string;
  LAVGQ5: string;
  TWAQ5: string;
  CRITERIONTIMESEC: string;
  LZF10: string;
  LZF50: string;
  LZF90: string;
  LZF95: string;
  LZFVAR: string;
  LCF10: string;
  LCF50: string;
  LCF90: string;
  LCF95: string;
  LCFVAR: string;
  LAF10: string;
  LAF50: string;
  LAF90: string;
  LAF95: string;
  LAFVAR: string;
  OVERLOADTIMESEC: string;
  VARLN: string;
  LEPDVAL: string;
  LEX8HVAL: string;
};

export type PapaError = {
  code: string;
  message: string;
  row: number;
  type: string;
};

export type PapaMeta = {
  delimiter: string;
  linebreak: string;
  aborted: boolean;
  truncated: boolean;
  cursor: number;
  fields: string[];
};

export type ParsedPeriodData = {
  data: PeriodData[];
  errors: PapaError[] | null;
  meta: PapaMeta;
};
